# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  Build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site
    - name: Build doxy
      id: build_doxy
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
         doxyfile-path: 'Docs/AdeNote_Configuration.config'
         working-directory: '.'
    - name: Deploy to git pages
      id: deployment
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: Docs/html
        token: ${{ secrets.DEPLOY_PAGE_TOKEN }}
