# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy documentation

on:
  push:
    branches: [ "master" ]
    paths-ignore:
     - '.gitignore'
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  Build:
    environment:
      name: github-pages
      url: 'https://adeola-aderibigbe.github.io/AdeNoteAPI/html'
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x  
    - name: build test coverage xml
      run: dotnet test AdeNote.Tests/AdeNote.Tests.csproj --collect:"XPlat Code Coverage"
    - name: Generate code coverage report
      uses: im-open/code-coverage-report-generator@4.9.2  
      with:
        reports: "AdeNote.Tests/TestResults/**/coverage.cobertura.xml"
        targetdir: "Docs/coverage"
        reporttypes: 'Html;MarkdownSummary'
        title: 'AdeNote Code Coverage'
        tag: '${{ github.workflow}}_${{ github.run_id }}'
        filefilters: '-Startup.cs;-Program.cs;'
        toolpath: 'reportgeneratortool'
    - name: Build doxygen documentation
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
       working-directory: 'AdeNote.API'
       doxyfile-path: 'Docs/html'
    - name: add and commit code coverage to gh-page
      run: |
         git config --global user.name 'Adeola.Aderibigbe'
         git config --global user.email 'adeola.aderibigbe@cyphercrescent.com'
         git add Docs/coverage/*.html
         git add Docs/coverage/*.css
         git add Docs/coverage/*.js
         git add Docs/coverage/*.svg
         git add Docs/html/* .
         git commit -a -m "Add recent code coverage"
         git merge --no-ff
         git config pull.rebase true 
         git pull origin gh-pages --allow-unrelated-histories
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
   


        
