# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy documentation

on:
  push:
    branches: [ "master" ]
    paths-ignore:
     - '.gitignore'
permissions:
   contents: write

jobs:
  Build:
    environment:
      name: github-pages
      url: 'https://adeola-aderibigbe.github.io/AdeNoteAPI/'
    runs-on: ubuntu-latest
   
    steps:
    - name: Deploy to git pages
      id: deployment
      uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
      with:
        folder: Docs/html
        config_file: Docs/AdeNote_Configuration.config
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: gh-pages


        
