# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy documentation

on:
  push:
    branches: [ "master" ]
    paths-ignore:
     - '.gitignore'
permissions:
   contents: write

jobs:
  Build:
    environment:
      name: github-pages
      url: 'https://adeola-aderibigbe.github.io/AdeNoteAPI/html'
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x  
    - name: build test coverage xml
      run: dotnet test AdeNote.Tests/AdeNote.Tests.csproj --collect:"XPlat Code Coverage"
    - name: Generate code coverage report
      uses: im-open/code-coverage-report-generator@4.9.2  
      with:
        reports: "AdeNote.Tests/TestResults/**/coverage.cobertura.xml"
        targetdir: "Docs/html/coverage"
        format: markdown
        title: 'AdeNote Code Coverage'
        tag: '${{ github.workflow}}_${{ github.run_id }}'
        filefilters: '-Startup.cs;-Program.cs;-*.cshtml'
        toolpath: 'reportgeneratortool'
    - name: Deploy to gh-page
      uses: github/branch-deploy@v1.1.0
      with:
       stable_branch: gh-pages
    - name: Deploy to git pages
      id: deployment
      uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
      with:
        folder: Docs/html
        config_file: Docs/AdeNote_Configuration.config
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: gh-pages


        
