# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  Build:
    environment:
      name: github-pages
      url: 'https://adeola-aderibigbe.github.io/AdeNoteAPI/'
    runs-on: ubuntu-latest
   
    steps:
    - name: Deploy to git pages
      id: deployment
      uses: DenverCoder1/doxygen-github-pages-action@v1
      with:
        folder: Docs/html
        github_token: ${{secrets.GITHUB_TOKEN}}


        
